### ISSUE TITLE
Ask for help -- how to modify printing parameters

### ISSUE THREAD

**Issue by kkzzzz0922** [calculon-ai/calculon#1]
Modify def display_stats(self): Modify the parameters in the log as comment f"Sample rate: {self.get_sample_rate():.2f};\n". But still no change in printing in centos linux. I want to ask you why

**Comment by nicmcd** [comment]
You can turn the log on with `./bin/calculon -v DEBUG ...` 
Also, display_stats is used for final output when its going to the console. If the output is going to a JSON file, it isn't used.

**Comment by kkzzzz0922** [comment]
First thanks you for replying，I only want to output in console，but printing was not change after modify  display_stats funcation, for example shield a line of code ，But still no change in printing.  so I want to ask some help to slove the problem。

**Comment by Pastens** [comment]
> First thanks you for replying，I only want to output in console，but printing was not change after modify display_stats funcation, for example shield a line of code ，But still no change in printing. so I want to ask some help to slove the problem。

Firstly, you should check whether you "make install" the calculon before. If so, you should do that again to reinstall the calculon to you environment, otherwise running calculon will firstly use the former version. If not and you run calculon as './bin/calculom' way, it shouldn't happen.

**Comment by kkzzzz0922** [comment]
Reinstall calculon，but no change.   thanks you for replying.  The following screenshot is the reason why I want to ask for help 
run ./bin/calculon llm models/megatron-1T.json examples/3072_t4_p64_d12_mbs4_full.json systems/a100_80g.json -  
modify code：![image](https://github.com/calculon-ai/calculon/assets/75347366/a896bbf5-94be-4f8e-a91d-3152776b3d4a)
output：![image](https://github.com/calculon-ai/calculon/assets/75347366/85f13779-180c-419c-bc60-81393e2c620d)
add output after modify bin/calculon, but  I want to change logging output 
![image](https://github.com/calculon-ai/calculon/assets/75347366/732b8e54-8a1a-4878-827e-d2282a356cee)

**Comment by Pastens** [comment]
> Reinstall calculon，but no change. thanks you for replying. The following screenshot is the reason why I want to ask for help run ./bin/calculon llm models/megatron-1T.json examples/3072_t4_p64_d12_mbs4_full.json systems/a100_80g.json - modify code：![image](https://user-images.githubusercontent.com/75347366/256100309-a896bbf5-94be-4f8e-a91d-3152776b3d4a.png) output：![image](https://user-images.githubusercontent.com/75347366/256100340-85f13779-180c-419c-bc60-81393e2c620d.png) add output after modify bin/calculon, but I want to change logging output ![image](https://user-images.githubusercontent.com/75347366/256101367-732b8e54-8a1a-4878-827e-d2282a356cee.png)

That's weird. It works in my environment. You'd better check your PYTHONPATH in your env and installation path carefully, to avoid reinstall to other places other than overwrite the version you install before.

**Comment by nicmcd** [comment]
I would recommend NOT installing calculon if you intend on modifying it. Otherwise you may not know whether the installed version or the development version is being run. Just use direct commands to run it with the right path:

`PYTHONPATH=. ./bin/calculon -v DEBUG llm ...`

**Comment by kkzzzz0922** [comment]
Finally I run ./bin/calculon -v DEBUG llm models/megatron-1T.json examples/3072_t4_p64_d12_mbs4_full.json systems/a100_80g.json -    I found the parameter I wanted .Thank you 2 big guys , but I still want to know why the log cannot be modified.

**Comment by nicmcd** [comment]
@kkzzzz0922 when you say "the log", what are you referring to? Are you referring to the actual logger output:
https://github.com/calculon-ai/calculon/blob/main/calculon/llm/llm.py#L1286
Are you referring to the console based output numbers reported when you give the "llm" command a "-" for the output?
Are you referring to the JSON file output?

From the conversation I mentioned above, it seems like you are referring to the console based output. The only reason that changing the code doesn't result in a different output is that the code you are changing isn't actually getting run. This is the reason that I DO NOT suggest installing calculon. Just run it directly where it is like I said above. Make sure if you previously installed it you uninstall it.
