### ISSUE TITLE
How to calibrate the system parameters accurately?

### ISSUE THREAD

**Issue by dageita** [calculon-ai/calculon#12]
Some parameters are the rated parameters of the GPU, while others such as efficiency seem to require additional calibration. How to calibrate the efficiency of network or flopps?
{
  "matrix" : {
    "float16": {
      "tflops": 312,
      "gflops_efficiency": [
        [128, 0.99],
        [16, 0.9],
        [1, 0.6],
        [0, 0.1]
      ]
    }
  },
  "vector": {
    "float16": {
      "tflops": 78,
      "gflops_efficiency": [
        [16, 0.95],
        [1, 0.5],
        [0, 0.1]
      ]
    }
  },
  "mem1": {
    "GiB": 80,
    "GBps": 1935,
    "MB_efficiency": [
      [100, 0.95],
      [10, 0.90],
      [1, 0.7],
      [0, 0.3]
    ]
  },
  "mem2": {
    "GiB": 512,
    "GBps": 32,
    "MB_efficiency": [
      [100, 0.95],
      [10, 0.9],
      [1, 0.7],
      [0, 0.3]
    ]
  },
  "processing_mode": "no_overlap",
  "networks": [
    {
      "bandwidth": 200,
      "efficiency": 0.7,
      "size": 2,
...
}

**Comment by nicmcd** [comment]
The best thing you can do for calibration is to run experiments on real hardware and derive efficiency tables. I know it is annoying :(

**Comment by dageita** [comment]
> The best thing you can do for calibration is to run experiments on real hardware and derive efficiency tables. I know it is annoying :(

Thanks for your reply very much, so what tools should be used to measure the gflops effiency, memory efficiency corresponding to different sizes of data blocks, as well as the nvlink efficiency corresponding to different data blocks?

**Comment by dageita** [comment]
For example, how can I test GEMM calculation by CUTLASS to obtain a representative efficiency value for system configs in Calculon?
