### ISSUE TITLE
Questions about the communication op factor and offset in the provided examples

### ISSUE THREAD

**Issue by yutian-mt** [calculon-ai/calculon#7]
for example: https://github.com/calculon-ai/calculon/blob/main/systems/a100_80g.json,
```
{
 "networks": [
    {
      "bandwidth": 300,
      "efficiency": 0.65,
      "size": 8,
      "latency": 0.00001,
      "ops": {
        "p2p": [1.0, null],
        "reduce_scatter": [1.5, -1],
        "all_gather": [1.5, -1],
        "all_reduce": [2.0, -1]
      },
      "must_be_filled": true,
      "processor_usage": 0.15
    },{
      "bandwidth": 25,
      "efficiency": 0.9,
      "size": 65536,
      "latency": 0.00002,
      "ops": {
        "p2p": [1.0, null],
        "reduce_scatter": [1.0, 0],
        "all_gather": [1.0, 0],
        "all_reduce": [1.0, 0]
      },
      "must_be_filled": false,
      "processor_usage": 0.02
    }
}
```
I am confused. I understand that the scalar values for 'all_reduce,' 'all_gather,' and 'reduce_scatter' in network 0/1 should be (2, 1, 1), offsets should be -1. Why are there other values present?

**Comment by nicmcd** [comment]
The first number is a relative efficiency factor for that op assuming some algorithm. For example, if the AllReduce size is N total bytes, a standard ring-base AR implementation would send 2N bytes from each processor. If the network supports in-network collectives, this can be reduced to 1N. This is the first number. 

The second number yields an ability to model how the algorithm calculates the amount of bytes sent. Some algorithms have a P-1 factor in there. For example, a standard ring-based AllGather of total size N, only requires (P-1)/P * N bytes sent from each processor instead of the full N. Based on the value of P (participants in the collective), this can change the performance quite a bit. When the second number is "-1" it does the P-1 trick. When it is 0, it does not.

**Comment by yutian-mt** [comment]
> The first number is a relative efficiency factor for that op assuming some algorithm. For example, if the AllReduce size is N total bytes, a standard ring-base AR implementation would send 2N bytes from each processor. If the network supports in-network collectives, this can be reduced to 1N. This is the first number.
> 
> The second number yields an ability to model how the algorithm calculates the amount of bytes sent. Some algorithms have a P-1 factor in there. For example, a standard ring-based AllGather of total size N, only requires (P-1)/P * N bytes sent from each processor instead of the full N. Based on the value of P (participants in the collective), this can change the performance quite a bit. When the second number is "-1" it does the P-1 trick. When it is 0, it does not.

Got it. I have another question: why is the scalar for network0 all_gather/reduce_scatter 1.5 instead of 1.0( I assume this is the standard ring-based implementation, is that correct) ?

**Comment by dageita** [comment]
How to explain the difference between two networks? It seems that the first one is the total 300GB/s bandwidth of NVLink, while the second one is the 25GB/s bandwidth of a single NVLink link?

**Comment by nicmcd** [comment]
Calculon is protocol agnostic. In this example, it is meant for network[0] to be NVLink at 300 GB/s and network[1] to be Infiniband HDR 200 GB/s.

**Comment by dageita** [comment]
> > The first number is a relative efficiency factor for that op assuming some algorithm. For example, if the AllReduce size is N total bytes, a standard ring-base AR implementation would send 2N bytes from each processor. If the network supports in-network collectives, this can be reduced to 1N. This is the first number.
> > The second number yields an ability to model how the algorithm calculates the amount of bytes sent. Some algorithms have a P-1 factor in there. For example, a standard ring-based AllGather of total size N, only requires (P-1)/P * N bytes sent from each processor instead of the full N. Based on the value of P (participants in the collective), this can change the performance quite a bit. When the second number is "-1" it does the P-1 trick. When it is 0, it does not.
> 
> Got it. I have another question: why is the scalar for network0 all_gather/reduce_scatter 1.5 instead of 1.0( I assume this is the standard ring-based implementation, is that correct) ?

I also have another question: why the scalar and offset of NVLink is different with IB? I think whether it is intra-nodes or inter-nodes, the work done for collective communication is the same.

**Comment by ljoan1234** [comment]
> > The first number is a relative efficiency factor for that op assuming some algorithm. For example, if the AllReduce size is N total bytes, a standard ring-base AR implementation would send 2N bytes from each processor. If the network supports in-network collectives, this can be reduced to 1N. This is the first number.
> > The second number yields an ability to model how the algorithm calculates the amount of bytes sent. Some algorithms have a P-1 factor in there. For example, a standard ring-based AllGather of total size N, only requires (P-1)/P * N bytes sent from each processor instead of the full N. Based on the value of P (participants in the collective), this can change the performance quite a bit. When the second number is "-1" it does the P-1 trick. When it is 0, it does not.
> 
> Got it. I have another question: why is the scalar for network0 all_gather/reduce_scatter 1.5 instead of 1.0( I assume this is the standard ring-based implementation, is that correct) ?
I also have this question, can you help me answer it？
