### ISSUE TITLE
Different A100 Systems Used in Validation

### ISSUE THREAD

**Issue by HanjiangWu313** [calculon-ai/calculon#8]
I am using the tool and trying to change the system parameters for testing, and I found out that in the reference validation, different A100 (A100g v.s A100e) systems are used with different compute and memory settings. May I ask what is the difference between the two systems, since my understanding is that they should have the same parameters? Thanks in advance!

**Comment by nicmcd** [comment]
A100e was originally the same as A100g (the 80G version) but with 80 exabytes of memory. However, over time A100e got stale. We suggest creating your own system config based on benchmark results.
